### ISSUE TITLE
What does MasteringDisplayMaxLuminance stand for?

### ISSUE THREAD

**Issue by Kiyamou** [age1988/vapoursynth-tonemapping#1]
When I try to use this script, I get the error.
`No key named MasteringDisplayMaxLuminance exists`

I know `MasteringDisplayMaxLuminance` is a parameter in ffms2. However, VapourSynth's Python API doesn't seem to have it.

So could you explain the meaning of this code?
(https://github.com/age1988/vapoursynth-tonemapping/blob/master/age_tm.py#L223)

```python
if source_peak is None:
    source_peak=c.get_frame(0).props.MasteringDisplayMaxLuminance
```

There is my script and error info.

```python
import vapoursynth as vs
import age_tm as tm

core = vs.get_core()

src = r"..."
src = core.ffms2.Source(src)
res = tm.reinhard_yuv(src, target_nits=120, source_peak=None)

res.set_output()
```

```
Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 872, in vapoursynth.VideoProps.__getattr__
File "src\cython\vapoursynth.pyx", line 772, in vapoursynth.VideoProps.__getitem__
KeyError: 'No key named MasteringDisplayMaxLuminance exists'

......

File "C:\Program Files\Python38\lib\site-packages\age_tm.py", line 224, in reinhard_yuv
source_peak = c.get_frame(0).props.MasteringDisplayMaxLuminance
File "src\cython\vapoursynth.pyx", line 874, in vapoursynth.VideoProps.__getattr__
AttributeError
```

Thanks.

**Comment by age1988** [comment]
That error happens because Vapoursynth doesn't find the metadata in the video file

**Comment by Kiyamou** [comment]
I get it. Thanks:)
